### ISSUE TITLE
Get more details

### ISSUE THREAD

**Issue by ZTFitru** [ZTFitru/osCorp-Media#2]
As a user I want to select an article and read about it so i can be informed about the topic.

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)
